storagedir=/tmp_mnt/scratch/knuenz/Polarization/Upsilon
#macdir=/Users/valentinknuenz/usr/local/workspace/UpsilonPol/macros/polFit
AFSdir=/afs/hephy.at/scratch/k/knuenz/CMSSW_4_2_4_patch2/src/UpsilonPol/macros/polFit

DataToy=Data

for JobID in Data_TheGreatRun_10B_Apr18_NewestCentrals;do

echo $JobID
cp -r ${storagedir}/${DataToy}/${JobID}/Figures/ ${AFSdir}/Figures${DataToy}/${JobID}

#rm -r ${AFSdir}/Figures${DataToy}/${JobID}/Figures/

done



cp ../Addition1_Ups1S_Data_TheGreatRun_10B_May11_NewestCentrals/results_Fit1_1SUps_rap1_pT7.root results_Fit26_1SUps_rap1_pT7.root
cp ../Addition1_Ups1S_Data_TheGreatRun_10B_May11_NewestCentrals/results_Fit2_1SUps_rap1_pT7.root results_Fit27_1SUps_rap1_pT7.root
cp ../Addition2_Ups1S_Data_TheGreatRun_10B_May11_NewestCentrals/results_Fit1_1SUps_rap1_pT7.root results_Fit28_1SUps_rap1_pT7.root
cp ../Addition2_Ups1S_Data_TheGreatRun_10B_May11_NewestCentrals/results_Fit2_1SUps_rap1_pT7.root results_Fit29_1SUps_rap1_pT7.root
cp ../Addition3_Ups1S_Data_TheGreatRun_10B_May11_NewestCentrals/results_Fit1_1SUps_rap1_pT7.root results_Fit30_1SUps_rap1_pT7.root
cp ../Addition3_Ups1S_Data_TheGreatRun_10B_May11_NewestCentrals/results_Fit2_1SUps_rap1_pT7.root results_Fit31_1SUps_rap1_pT7.root
cp ../Addition4_Ups1S_Data_TheGreatRun_10B_May11_NewestCentrals/results_Fit1_1SUps_rap1_pT7.root results_Fit32_1SUps_rap1_pT7.root
cp ../Addition4_Ups1S_Data_TheGreatRun_10B_May11_NewestCentrals/results_Fit2_1SUps_rap1_pT7.root results_Fit33_1SUps_rap1_pT7.root
cp ../Addition5_Ups1S_Data_TheGreatRun_10B_May11_NewestCentrals/results_Fit1_1SUps_rap1_pT7.root results_Fit34_1SUps_rap1_pT7.root
cp ../Addition5_Ups1S_Data_TheGreatRun_10B_May11_NewestCentrals/results_Fit2_1SUps_rap1_pT7.root results_Fit35_1SUps_rap1_pT7.root
cp ../Addition6_Ups1S_Data_TheGreatRun_10B_May11_NewestCentrals/results_Fit1_1SUps_rap1_pT7.root results_Fit36_1SUps_rap1_pT7.root
cp ../Addition6_Ups1S_Data_TheGreatRun_10B_May11_NewestCentrals/results_Fit2_1SUps_rap1_pT7.root results_Fit37_1SUps_rap1_pT7.root
cp ../Addition7_Ups1S_Data_TheGreatRun_10B_May11_NewestCentrals/results_Fit1_1SUps_rap1_pT7.root results_Fit38_1SUps_rap1_pT7.root
cp ../Addition7_Ups1S_Data_TheGreatRun_10B_May11_NewestCentrals/results_Fit2_1SUps_rap1_pT7.root results_Fit39_1SUps_rap1_pT7.root
cp ../Addition8_Ups1S_Data_TheGreatRun_10B_May11_NewestCentrals/results_Fit1_1SUps_rap1_pT7.root results_Fit40_1SUps_rap1_pT7.root
cp ../Addition8_Ups1S_Data_TheGreatRun_10B_May11_NewestCentrals/results_Fit2_1SUps_rap1_pT7.root results_Fit41_1SUps_rap1_pT7.root
cp ../Addition9_Ups1S_Data_TheGreatRun_10B_May11_NewestCentrals/results_Fit1_1SUps_rap1_pT7.root results_Fit42_1SUps_rap1_pT7.root
cp ../Addition9_Ups1S_Data_TheGreatRun_10B_May11_NewestCentrals/results_Fit2_1SUps_rap1_pT7.root results_Fit43_1SUps_rap1_pT7.root
cp ../Addition10_Ups1S_Data_TheGreatRun_10B_May11_NewestCentrals/results_Fit1_1SUps_rap1_pT7.root results_Fit44_1SUps_rap1_pT7.root
cp ../Addition10_Ups1S_Data_TheGreatRun_10B_May11_NewestCentrals/results_Fit2_1SUps_rap1_pT7.root results_Fit45_1SUps_rap1_pT7.root
cp ../Addition11_Ups1S_Data_TheGreatRun_10B_May11_NewestCentrals/results_Fit1_1SUps_rap1_pT7.root results_Fit46_1SUps_rap1_pT7.root
cp ../Addition11_Ups1S_Data_TheGreatRun_10B_May11_NewestCentrals/results_Fit2_1SUps_rap1_pT7.root results_Fit47_1SUps_rap1_pT7.root
cp ../Addition12_Ups1S_Data_TheGreatRun_10B_May11_NewestCentrals/results_Fit1_1SUps_rap1_pT7.root results_Fit48_1SUps_rap1_pT7.root
cp ../Addition12_Ups1S_Data_TheGreatRun_10B_May11_NewestCentrals/results_Fit2_1SUps_rap1_pT7.root results_Fit49_1SUps_rap1_pT7.root
cp ../Addition13_Ups1S_Data_TheGreatRun_10B_May11_NewestCentrals/results_Fit1_1SUps_rap1_pT7.root results_Fit50_1SUps_rap1_pT7.root
cp ../Addition13_Ups1S_Data_TheGreatRun_10B_May11_NewestCentrals/results_Fit2_1SUps_rap1_pT7.root results_FitX1_1SUps_rap1_pT7.root
cp ../Addition14_Ups1S_Data_TheGreatRun_10B_May11_NewestCentrals/results_Fit1_1SUps_rap1_pT7.root results_FitX2_1SUps_rap1_pT7.root
cp ../Addition14_Ups1S_Data_TheGreatRun_10B_May11_NewestCentrals/results_Fit2_1SUps_rap1_pT7.root results_FitX3_1SUps_rap1_pT7.root
cp ../Addition15_Ups1S_Data_TheGreatRun_10B_May11_NewestCentrals/results_Fit1_1SUps_rap1_pT7.root results_FitX4_1SUps_rap1_pT7.root
cp ../Addition15_Ups1S_Data_TheGreatRun_10B_May11_NewestCentrals/results_Fit2_1SUps_rap1_pT7.root results_FitX5_1SUps_rap1_pT7.root

cp ../Addition4_Ups1S_Data_TheGreatRun_10B_May11_NewestCentrals/results_Fit2_1SUps_rap2_pT7.root results_Fit33_1SUps_rap2_pT7.root
cp ../Addition5_Ups1S_Data_TheGreatRun_10B_May11_NewestCentrals/results_Fit1_1SUps_rap2_pT7.root results_Fit34_1SUps_rap2_pT7.root
cp ../Addition5_Ups1S_Data_TheGreatRun_10B_May11_NewestCentrals/results_Fit2_1SUps_rap2_pT7.root results_Fit35_1SUps_rap2_pT7.root
cp ../Addition6_Ups1S_Data_TheGreatRun_10B_May11_NewestCentrals/results_Fit1_1SUps_rap2_pT7.root results_Fit36_1SUps_rap2_pT7.root
cp ../Addition6_Ups1S_Data_TheGreatRun_10B_May11_NewestCentrals/results_Fit2_1SUps_rap2_pT7.root results_Fit37_1SUps_rap2_pT7.root
cp ../Addition7_Ups1S_Data_TheGreatRun_10B_May11_NewestCentrals/results_Fit1_1SUps_rap2_pT7.root results_Fit38_1SUps_rap2_pT7.root
cp ../Addition7_Ups1S_Data_TheGreatRun_10B_May11_NewestCentrals/results_Fit2_1SUps_rap2_pT7.root results_Fit39_1SUps_rap2_pT7.root
cp ../Addition8_Ups1S_Data_TheGreatRun_10B_May11_NewestCentrals/results_Fit1_1SUps_rap2_pT7.root results_Fit40_1SUps_rap2_pT7.root
cp ../Addition8_Ups1S_Data_TheGreatRun_10B_May11_NewestCentrals/results_Fit2_1SUps_rap2_pT7.root results_Fit41_1SUps_rap2_pT7.root
cp ../Addition9_Ups1S_Data_TheGreatRun_10B_May11_NewestCentrals/results_Fit1_1SUps_rap2_pT7.root results_Fit42_1SUps_rap2_pT7.root
cp ../Addition9_Ups1S_Data_TheGreatRun_10B_May11_NewestCentrals/results_Fit2_1SUps_rap2_pT7.root results_Fit43_1SUps_rap2_pT7.root
cp ../Addition10_Ups1S_Data_TheGreatRun_10B_May11_NewestCentrals/results_Fit1_1SUps_rap2_pT7.root results_Fit44_1SUps_rap2_pT7.root
cp ../Addition10_Ups1S_Data_TheGreatRun_10B_May11_NewestCentrals/results_Fit2_1SUps_rap2_pT7.root results_Fit45_1SUps_rap2_pT7.root
cp ../Addition11_Ups1S_Data_TheGreatRun_10B_May11_NewestCentrals/results_Fit1_1SUps_rap2_pT7.root results_Fit46_1SUps_rap2_pT7.root
cp ../Addition11_Ups1S_Data_TheGreatRun_10B_May11_NewestCentrals/results_Fit2_1SUps_rap2_pT7.root results_Fit47_1SUps_rap2_pT7.root
cp ../Addition12_Ups1S_Data_TheGreatRun_10B_May11_NewestCentrals/results_Fit1_1SUps_rap2_pT7.root results_Fit48_1SUps_rap2_pT7.root
cp ../Addition12_Ups1S_Data_TheGreatRun_10B_May11_NewestCentrals/results_Fit2_1SUps_rap2_pT7.root results_Fit49_1SUps_rap2_pT7.root
cp ../Addition13_Ups1S_Data_TheGreatRun_10B_May11_NewestCentrals/results_Fit1_1SUps_rap2_pT7.root results_Fit50_1SUps_rap2_pT7.root

cp ../Addition13_Ups1S_Data_TheGreatRun_10B_May11_NewestCentrals/results_Fit2_1SUps_rap2_pT7.root results_FitX1_1SUps_rap2_pT7.root
cp ../Addition14_Ups1S_Data_TheGreatRun_10B_May11_NewestCentrals/results_Fit1_1SUps_rap2_pT7.root results_FitX2_1SUps_rap2_pT7.root
cp ../Addition14_Ups1S_Data_TheGreatRun_10B_May11_NewestCentrals/results_Fit2_1SUps_rap2_pT7.root results_FitX3_1SUps_rap2_pT7.root
cp ../Addition1_Ups1S_Data_TheGreatRun_10B_May11_NewestCentrals/results_Fit1_1SUps_rap2_pT7.root results_FitX4_1SUps_rap2_pT7.root
cp ../Addition1_Ups1S_Data_TheGreatRun_10B_May11_NewestCentrals/results_Fit2_1SUps_rap2_pT7.root results_FitX5_1SUps_rap2_pT7.root
cp ../Addition2_Ups1S_Data_TheGreatRun_10B_May11_NewestCentrals/results_Fit1_1SUps_rap2_pT7.root results_FitX6_1SUps_rap2_pT7.root
cp ../Addition2_Ups1S_Data_TheGreatRun_10B_May11_NewestCentrals/results_Fit2_1SUps_rap2_pT7.root results_FitX7_1SUps_rap2_pT7.root
cp ../Addition3_Ups1S_Data_TheGreatRun_10B_May11_NewestCentrals/results_Fit1_1SUps_rap2_pT7.root results_FitX8_1SUps_rap2_pT7.root
cp ../Addition3_Ups1S_Data_TheGreatRun_10B_May11_NewestCentrals/results_Fit2_1SUps_rap2_pT7.root results_FitX9_1SUps_rap2_pT7.root
cp ../Addition4_Ups1S_Data_TheGreatRun_10B_May11_NewestCentrals/results_Fit1_1SUps_rap2_pT7.root results_FitX10_1SUps_rap2_pT7.root



cp Additions_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit1_1SUps_rap1_pT6.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit37_1SUps_rap1_pT6.root
cp Additions_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit2_1SUps_rap1_pT6.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit38_1SUps_rap1_pT6.root
cp Additions_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit3_1SUps_rap1_pT6.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit39_1SUps_rap1_pT6.root
cp Additions_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit4_1SUps_rap1_pT6.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit40_1SUps_rap1_pT6.root
cp Additions_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit5_1SUps_rap1_pT6.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit41_1SUps_rap1_pT6.root
cp Additions_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit6_1SUps_rap1_pT6.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit42_1SUps_rap1_pT6.root
cp Additions_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit7_1SUps_rap1_pT6.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit43_1SUps_rap1_pT6.root
cp Additions_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit8_1SUps_rap1_pT6.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit44_1SUps_rap1_pT6.root
cp Additions_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit9_1SUps_rap1_pT6.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit45_1SUps_rap1_pT6.root
cp Additions_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit10_1SUps_rap1_pT6.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit46_1SUps_rap1_pT6.root
cp Additions_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit11_1SUps_rap1_pT6.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit47_1SUps_rap1_pT6.root
cp Additions_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit12_1SUps_rap1_pT6.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit48_1SUps_rap1_pT6.root
cp Additions_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit13_1SUps_rap1_pT6.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit49_1SUps_rap1_pT6.root
cp Additions_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit14_1SUps_rap1_pT6.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit50_1SUps_rap1_pT6.root




cp Additions_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit1_1SUps_rap1_pT7.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit37_1SUps_rap1_pT7.root
cp Additions_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit2_1SUps_rap1_pT7.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit38_1SUps_rap1_pT7.root
cp Additions_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit3_1SUps_rap1_pT7.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit39_1SUps_rap1_pT7.root
cp Additions_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit4_1SUps_rap1_pT7.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit40_1SUps_rap1_pT7.root
cp Additions_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit5_1SUps_rap1_pT7.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit41_1SUps_rap1_pT7.root
cp Additions_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit6_1SUps_rap1_pT7.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit42_1SUps_rap1_pT7.root
cp Additions_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit7_1SUps_rap1_pT7.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit43_1SUps_rap1_pT7.root
cp Additions_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit8_1SUps_rap1_pT7.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit44_1SUps_rap1_pT7.root
cp Additions_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit9_1SUps_rap1_pT7.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit45_1SUps_rap1_pT7.root
cp Additions_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit10_1SUps_rap1_pT7.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit46_1SUps_rap1_pT7.root
cp Additions_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit11_1SUps_rap1_pT7.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit47_1SUps_rap1_pT7.root
cp Additions_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit12_1SUps_rap1_pT7.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit48_1SUps_rap1_pT7.root
cp Additions_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit13_1SUps_rap1_pT7.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit49_1SUps_rap1_pT7.root
cp Additions_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit14_1SUps_rap1_pT7.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit50_1SUps_rap1_pT7.root

cp Additions_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit15_1SUps_rap1_pT7.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit29_1SUps_rap1_pT7.root
cp Additions_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit16_1SUps_rap1_pT7.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit30_1SUps_rap1_pT7.root
cp Additions_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit17_1SUps_rap1_pT7.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit31_1SUps_rap1_pT7.root
cp Additions_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit18_1SUps_rap1_pT7.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit32_1SUps_rap1_pT7.root
cp Additions_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit19_1SUps_rap1_pT7.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit33_1SUps_rap1_pT7.root
cp Additions_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit20_1SUps_rap1_pT7.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit34_1SUps_rap1_pT7.root
cp Additions_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit21_1SUps_rap1_pT7.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit35_1SUps_rap1_pT7.root
cp Additions_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit22_1SUps_rap1_pT7.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit36_1SUps_rap1_pT7.root

cp Additions2_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit1_2SUps_rap1_pT10.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit29_2SUps_rap1_pT10.root
cp Additions2_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit2_2SUps_rap1_pT10.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit30_2SUps_rap1_pT10.root
cp Additions2_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit3_2SUps_rap1_pT10.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit31_2SUps_rap1_pT10.root
cp Additions2_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit4_2SUps_rap1_pT10.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit32_2SUps_rap1_pT10.root
cp Additions2_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit5_2SUps_rap1_pT10.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit33_2SUps_rap1_pT10.root
cp Additions2_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit6_2SUps_rap1_pT10.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit34_2SUps_rap1_pT10.root
cp Additions2_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit7_2SUps_rap1_pT10.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit35_2SUps_rap1_pT10.root
cp Additions2_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit8_2SUps_rap1_pT10.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit36_2SUps_rap1_pT10.root
cp Additions2_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit9_2SUps_rap1_pT10.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit37_2SUps_rap1_pT10.root
cp Additions2_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit10_2SUps_rap1_pT10.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit38_2SUps_rap1_pT10.root
cp Additions2_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit11_2SUps_rap1_pT10.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit39_2SUps_rap1_pT10.root
cp Additions2_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit12_2SUps_rap1_pT10.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit40_2SUps_rap1_pT10.root
cp Additions2_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit13_2SUps_rap1_pT10.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit41_2SUps_rap1_pT10.root
cp Additions2_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit14_2SUps_rap1_pT10.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit42_2SUps_rap1_pT10.root
cp Additions2_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit15_2SUps_rap1_pT10.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit43_2SUps_rap1_pT10.root
cp Additions2_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit16_2SUps_rap1_pT10.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit44_2SUps_rap1_pT10.root
cp Additions2_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit17_2SUps_rap1_pT10.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit45_2SUps_rap1_pT10.root
cp Additions2_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit18_2SUps_rap1_pT10.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit46_2SUps_rap1_pT10.root
cp Additions2_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit19_2SUps_rap1_pT10.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit47_2SUps_rap1_pT10.root
cp Additions2_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit20_2SUps_rap1_pT10.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit48_2SUps_rap1_pT10.root
cp Additions2_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit21_2SUps_rap1_pT10.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit49_2SUps_rap1_pT10.root
cp Additions2_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit22_2SUps_rap1_pT10.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit50_2SUps_rap1_pT10.root




cp Additions_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit1_2SUps_rap1_pT9.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit27_2SUps_rap1_pT9.root
cp Additions_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit2_2SUps_rap1_pT9.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit28_2SUps_rap1_pT9.root
cp Additions_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit3_2SUps_rap1_pT9.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit29_2SUps_rap1_pT9.root
cp Additions_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit4_2SUps_rap1_pT9.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit30_2SUps_rap1_pT9.root
cp Additions_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit5_2SUps_rap1_pT9.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit31_2SUps_rap1_pT9.root
cp Additions_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit6_2SUps_rap1_pT9.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit32_2SUps_rap1_pT9.root
cp Additions_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit7_2SUps_rap1_pT9.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit33_2SUps_rap1_pT9.root
cp Additions_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit8_2SUps_rap1_pT9.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit34_2SUps_rap1_pT9.root
cp Additions1_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit1_2SUps_rap1_pT9.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit35_2SUps_rap1_pT9.root
cp Additions1_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit2_2SUps_rap1_pT9.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit36_2SUps_rap1_pT9.root
cp Additions1_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit3_2SUps_rap1_pT9.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit37_2SUps_rap1_pT9.root
cp Additions1_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit4_2SUps_rap1_pT9.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit38_2SUps_rap1_pT9.root
cp Additions1_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit5_2SUps_rap1_pT9.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit39_2SUps_rap1_pT9.root
cp Additions1_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit6_2SUps_rap1_pT9.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit40_2SUps_rap1_pT9.root
cp Additions1_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit7_2SUps_rap1_pT9.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit41_2SUps_rap1_pT9.root
cp Additions1_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit8_2SUps_rap1_pT9.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit42_2SUps_rap1_pT9.root
cp Additions2_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit1_2SUps_rap1_pT9.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit43_2SUps_rap1_pT9.root
cp Additions2_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit2_2SUps_rap1_pT9.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit44_2SUps_rap1_pT9.root
cp Additions2_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit3_2SUps_rap1_pT9.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit45_2SUps_rap1_pT9.root
cp Additions2_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit4_2SUps_rap1_pT9.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit46_2SUps_rap1_pT9.root
cp Additions2_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit5_2SUps_rap1_pT9.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit47_2SUps_rap1_pT9.root
cp Additions2_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit6_2SUps_rap1_pT9.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit48_2SUps_rap1_pT9.root
cp Additions2_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit7_2SUps_rap1_pT9.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit49_2SUps_rap1_pT9.root
cp Additions2_Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit8_2SUps_rap1_pT9.root Data_TheGreatApproval_June17_NewestCentrals_SOFT_SOFT/results_Fit50_2SUps_rap1_pT9.root

scp knuenz@lxplus250.cern.ch:/tmp/zhlinl/rootfiles/results_1SUps_rap1_pT6.root .
scp knuenz@lxplus250.cern.ch:/tmp/zhlinl/rootfiles/results_1SUps_rap1_pT7.root .
scp knuenz@lxplus250.cern.ch:/tmp/zhlinl/rootfiles/results_1SUps_rap1_pT8.root .
scp knuenz@lxplus250.cern.ch:/tmp/zhlinl/rootfiles/results_1SUps_rap1_pT9.root .
scp knuenz@lxplus250.cern.ch:/tmp/zhlinl/rootfiles/results_1SUps_rap1_pT10.root .
scp knuenz@lxplus250.cern.ch:/tmp/zhlinl/rootfiles/results_1SUps_rap2_pT6.root .
scp knuenz@lxplus250.cern.ch:/tmp/zhlinl/rootfiles/results_1SUps_rap2_pT7.root .
scp knuenz@lxplus250.cern.ch:/tmp/zhlinl/rootfiles/results_1SUps_rap2_pT8.root .
scp knuenz@lxplus250.cern.ch:/tmp/zhlinl/rootfiles/results_1SUps_rap2_pT9.root .
scp knuenz@lxplus250.cern.ch:/tmp/zhlinl/rootfiles/results_1SUps_rap2_pT10.root .

scp knuenz@lxplus250.cern.ch:/tmp/zhlinl/rootfiles/results_2SUps_rap1_pT6.root .
scp knuenz@lxplus250.cern.ch:/tmp/zhlinl/rootfiles/results_2SUps_rap1_pT7.root .
scp knuenz@lxplus250.cern.ch:/tmp/zhlinl/rootfiles/results_2SUps_rap1_pT8.root .
scp knuenz@lxplus250.cern.ch:/tmp/zhlinl/rootfiles/results_2SUps_rap1_pT9.root .
scp knuenz@lxplus250.cern.ch:/tmp/zhlinl/rootfiles/results_2SUps_rap1_pT10.root .
scp knuenz@lxplus250.cern.ch:/tmp/zhlinl/rootfiles/results_2SUps_rap2_pT6.root .
scp knuenz@lxplus250.cern.ch:/tmp/zhlinl/rootfiles/results_2SUps_rap2_pT7.root .
scp knuenz@lxplus250.cern.ch:/tmp/zhlinl/rootfiles/results_2SUps_rap2_pT8.root .
scp knuenz@lxplus250.cern.ch:/tmp/zhlinl/rootfiles/results_2SUps_rap2_pT9.root .
scp knuenz@lxplus250.cern.ch:/tmp/zhlinl/rootfiles/results_2SUps_rap2_pT10.root .

scp knuenz@lxplus250.cern.ch:/tmp/zhlinl/rootfiles/results_3SUps_rap1_pT6.root .
scp knuenz@lxplus250.cern.ch:/tmp/zhlinl/rootfiles/results_3SUps_rap1_pT7.root .
scp knuenz@lxplus250.cern.ch:/tmp/zhlinl/rootfiles/results_3SUps_rap1_pT8.root .
scp knuenz@lxplus250.cern.ch:/tmp/zhlinl/rootfiles/results_3SUps_rap1_pT9.root .
scp knuenz@lxplus250.cern.ch:/tmp/zhlinl/rootfiles/results_3SUps_rap1_pT10.root .
scp knuenz@lxplus250.cern.ch:/tmp/zhlinl/rootfiles/results_3SUps_rap2_pT6.root .
scp knuenz@lxplus250.cern.ch:/tmp/zhlinl/rootfiles/results_3SUps_rap2_pT7.root .
scp knuenz@lxplus250.cern.ch:/tmp/zhlinl/rootfiles/results_3SUps_rap2_pT8.root .
scp knuenz@lxplus250.cern.ch:/tmp/zhlinl/rootfiles/results_3SUps_rap2_pT9.root .
scp knuenz@lxplus250.cern.ch:/tmp/zhlinl/rootfiles/results_3SUps_rap2_pT10.root .
